esphome:
  name: hlk_ld2402
  friendly_name: HLK-LD2402 Radar

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG
  logs:
    uart: DEBUG
    hlk_ld2402: DEBUG

# Enable Home Assistant API
api:

ota:
  password: "your_ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Hlk-Ld2402 Fallback Hotspot"
    password: "your_ap_password"

captive_portal:

# UART configuration for the HLK-LD2402
uart:
  tx_pin: GPIO1  # D10 (TX)
  rx_pin: GPIO3  # D9 (RX)
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1
  id: uart_bus

# External component configuration
external_components:
  - source:
      type: local
      path: components  # Point to the components directory, not components/hlk_ld2402
    components: [ hlk_ld2402 ]  # Explicitly list the component

# HLK-LD2402 radar component configuration
hlk_ld2402:
  uart_id: uart_bus
  id: radar_sensor
  max_distance: 10.0  # Maximum detection distance in meters
  timeout: 5  # Timeout in seconds

# Configure the Distance sensor separately as a platform
sensor:
  - platform: hlk_ld2402
    id: radar_distance
    name: "Distance"
    hlk_ld2402_id: radar_sensor
    device_class: distance
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    icon: "mdi:radar"
    throttle: 1000ms  # Update every second
